// <auto-generated />
namespace Lendship.Backend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class CreateEvaluations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreateEvaluations));
        
        string IMigrationMetadata.Id
        {
            get { return "202110032150597_CreateEvaluations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
