/*
 * Simple Inventory API
 *
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using Lendship.Backend.DTO;
using Microsoft.AspNetCore.Authorization;
using Lendship.Backend.Interfaces.Services;

namespace Lendship.Backend.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    [Authorize]
    [ApiController]
    [Route("[controller]")]
    public class CategoryController : ControllerBase
    {
        private readonly ICategoryService _categoryService;

        public CategoryController(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        /// <summary>
        /// get all categories
        /// </summary>
        /// <remarks>Gets all categories</remarks>
        /// <response code="200">categories</response>
        /// <response code="400">bad request</response>
        /// <response code="401"></response>
        [HttpGet]
        public virtual IActionResult GetCategories()
        {
            var categories = _categoryService.GetCategories();

            if (categories != null)
            {
                return new ObjectResult(JsonConvert.SerializeObject(categories));
            }

            return this.BadRequest("No category found.");
        }
    }
}
