/*
 * Simple Inventory API
 *
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using Lendship.Backend.Interfaces.Services;
using Microsoft.AspNetCore.Mvc;

namespace Lendship.Backend.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    [Route("[controller]")]
    public class InformationsController : ControllerBase
    {
        private readonly IInformationsService _infoService;

        public InformationsController(IInformationsService infoService)
        {
            _infoService = infoService;
        }

        /// <summary>
        /// get informations
        /// </summary>
        /// <remarks>Gets the informations to the about page</remarks>
        /// <response code="200">Infromations</response>
        /// <response code="400">bad request</response>
        [HttpGet]
        public virtual IActionResult GetInformations()
        {
            var infos = _infoService.GetInformations();

            if (infos != null)
            {
                return new ObjectResult(infos.ToJson());
            }

            return this.BadRequest("Closed Group not found.");
        }
    }
}
